apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aim.configMapName" . }}
  labels:
    {{- include "aim.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
