{{- if not .Values.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aim.secretName" . }}
  labels:
    {{- include "aim.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
  {{- if and (not .Values.postgresql.enabled) .Values.externalDatabase.url (not .Values.externalDatabase.existingSecret) }}
  AIM_DATABASE_URL: {{ .Values.externalDatabase.url | quote }}
  {{- end }}
{{- end }}
