"""Add organizations and org_id

Revision ID: 4e96f612bade
Revises: a3b4c5d6e7f8
Create Date: 2026-05-02 12:27:26.014003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e96f612bade'
down_revision: Union[str, Sequence[str], None] = 'a3b4c5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    
    # --- Inject default organization ---
    default_org_id = '00000000-0000-0000-0000-000000000000'
    op.execute(f"INSERT INTO organizations (id, name, slug, created_at) VALUES ('{default_org_id}', 'Main', 'main', CURRENT_TIMESTAMP)")
    # -----------------------------------
    op.create_table('user_organizations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'org_id')
    )
    with op.batch_alter_table('agent_team_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_agent_team_profiles_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_approval_requests_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_audit_entries_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bot_action_audit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_bot_action_audit_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bot_connectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_bot_connectors_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bot_user_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_bot_user_links_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('detector_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_detector_history_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('detector_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_detector_rules_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_incidents_sla_targets', 'sla_targets', ['target_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_incidents_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ingest_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_ingest_log_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ingest_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_ingest_tokens_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('maintenance_windows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_maintenance_windows_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_mcp_servers_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_model_configs_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('runtime_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_runtime_config_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('session_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_session_messages_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('incident_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_sessions_agent_team_profiles', 'agent_team_profiles', ['agent_team_profile_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_sessions_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_sessions_workflow_profiles', 'workflow_profiles', ['workflow_profile_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_skills_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sla_targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_sla_targets_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('slos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_slos_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('uptime_samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_uptime_samples_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('uptime_samples_1h', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_uptime_samples_1h_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('uptime_samples_5m', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_uptime_samples_5m_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_org_id', sa.Uuid(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_users_organizations', 'organizations', ['primary_org_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('webhook_triggers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_webhook_triggers_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('workflow_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
        batch_op.create_foreign_key('fk_workflow_profiles_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('webhook_triggers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('primary_org_id')

    with op.batch_alter_table('uptime_samples_5m', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('uptime_samples_1h', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('uptime_samples', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('slos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('sla_targets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('incident_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('org_id')

    with op.batch_alter_table('session_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('runtime_config', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('maintenance_windows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('ingest_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('ingest_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('org_id')

    with op.batch_alter_table('detector_rules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('detector_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('bot_user_links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('bot_connectors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('bot_action_audit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('agent_team_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    op.drop_table('user_organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
